### ISSUE TITLE
Protocol sinff from basic functions

### ISSUE THREAD

**Issue by dclogicsCH** [kordian-kowalski/wz5005-control#1]
Do you have already a protocol sniff from the existing windows software?

**Comment by kordian-kowalski** [comment]
Not yet, but there's some protocol documentation available for WZ-6008, they seem to share the same protocol.
e.g.: http://www.icstation.com/480w-step-down-power-supply-module-controller-buck-voltage-converter-programmable-24in-display-p-14819.html 
So far I have determined that commands and responses are always 20 bytes:
- 1b static header
- 1b seemingly-static value
- 1b command
- 16x 1b command arguments / responses
- 1b checksum

The table in the link tells which argument index corresponds to what value, e.g. sending 0x2A with 16 0x00 arguments will result in 16 returned values, bytes 1-3 representing uptime, 4-5 cumulative energy ... and 15-16 unused (0x00).

**Comment by kordian-kowalski** [comment]
What is stopping me now is the checksum byte at the end, I'm not sure what checksum algo is being used there.

**Comment by kordian-kowalski** [comment]
I've started describing the protocol:
https://github.com/kordian-kowalski/wz5005-control/blob/main/protocol.md
